### PR TITLE
Add support for JSON in manifest API

### PR DESCRIPTION
**Pull request by jirutka**
This partially solves #43.

### CODE REVIEW

**Comment by jirutka** [comment]
@leafo Could you please look at this?

**Comment by leafo** [comment]
sorry about the delay, it's merged now: https://luarocks.org/manifest-5.1.json

**Comment by jirutka** [comment]
Great, thanks!

**Comment by scherenhaenden** [comment]
About this feature. I'm trying to build a Little program that look for dependencies in different packages systems like NPM, Node.js, Pip and so on. I'm running into CORS on this manifest... is there any documentation about it? I've been looking for any kind of documentation but i find none... this is like my last resort...

**Comment by leafo** [comment]
@scherenhaenden there is no cors on the json endpoint right now, you would have to use a server side request to access it

**Comment by scherenhaenden** [comment]
yep thanks... I Just decide to turn my app into a Electron app. The problem is not Just Lua... and also that Lua does not have a queryble endpoint... i think im gonna cache the manifest and do queries to that cache. 

Thanks for the fast answer, mate!

**Pull request closed without merging**
